version: '2.2'
services:
    sharelatex:
        restart: always
        image: sharelatex/sharelatex:with-texlive-full
        container_name: sharelatex
        depends_on:
            mongo:
                condition: service_healthy
            redis-overleaf:
                condition: service_started
        ports:
            - 8080:80
        links:
            - mongo
            - redis-overleaf
        stop_grace_period: 60s
        volumes:
            - /path/to/sharelatex_data:/var/lib/overleaf
        environment:

            OVERLEAF_APP_NAME: Overleaf Community Edition

            OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex

            # Same property, unfortunately with different names in
            # different locations
            OVERLEAF_REDIS_HOST: redis-overleaf
            REDIS_HOST: redis-overleaf

            ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'

            # Enables Thumbnail generation using ImageMagick
            ENABLE_CONVERSIONS: 'true'

            # Disables email confirmation requirement
            EMAIL_CONFIRMATION_DISABLED: 'true'

            # temporary fix for LuaLaTex compiles
            # see https://github.com/overleaf/overleaf/issues/695
            TEXMFVAR: /var/lib/overleaf/tmp/texmf-var


    mongo:
        restart: always
        image: mongo:5.0
        container_name: mongo
        command: ["--replSet", "rs0"]
        expose:
            - 27017
        volumes:
            - /path/to/mongo_data:/data/db
        healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5

    mongo-init-replica:
        image: mongo:5.0
        depends_on:
          - mongo
        command: ['bash', '-c', 'sleep 10 && mongo --eval "rs.initiate()" mongo/rs0']

    redis-overleaf:
        restart: always
        image: redis:5
        container_name: redis-overleaf
        expose:
            - 6379
        volumes:
            - /path/to/redis_data:/data
