services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: 1.20.6
      VIEW_DISTANCE: 10
      MEMORY: 4G
    volumes:
      - ./data:/data

volumes:
  data: {}