version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - 80:80 #http
      - 81:81 #config portal
      - 443:443 #https
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: <user>
      DB_MYSQL_PASSWORD: <password>
      DB_MYSQL_NAME: "npm"
    volumes:
      - /path/to/data/:/data
      - /path/to/letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: <password>
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: <user>
      MYSQL_PASSWORD: <password>
    volumes:
      - /path/to/data/mysql:/var/lib/mysql